# Generated by Django 5.2.16 on 2026-07-08 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='mediahub/')),
                ('asset_type', models.CharField(choices=[('image', 'Imagem'), ('pdf', 'PDF'), ('ebook', 'E-book'), ('book', 'Livro'), ('document', 'Documento'), ('certificate', 'Certificado'), ('technical', 'Documento técnico'), ('other', 'Outro')], default='document', max_length=32)),
                ('alt_text', models.CharField(blank=True, max_length=240)),
                ('credit', models.CharField(blank=True, max_length=180)),
                ('is_public', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ativo de mídia',
                'verbose_name_plural': 'ativos de mídia',
                'ordering': ('title',),
            },
        ),
    ]
