# Generated by Django 5.2.16 on 2026-07-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('axes', '0002_researchaxis_unit'),
        ('institutional', '0002_validate_and_add_institutional_constraints'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('work_type', models.CharField(choices=[('tcc', 'TCC'), ('monograph', 'Monografia'), ('scientific_initiation', 'Iniciação científica'), ('dissertation', 'Dissertação'), ('thesis', 'Tese'), ('other', 'Outro')], max_length=32)),
                ('course', models.CharField(blank=True, max_length=180)),
                ('institution', models.CharField(blank=True, max_length=220)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Palavras-chave separadas por vírgula.')),
                ('file', models.FileField(blank=True, upload_to='research/academic-works/')),
                ('external_url', models.URLField(blank=True)),
                ('editorial_status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=32)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_works', to='institutional.institutionalunit')),
            ],
            options={
                'verbose_name': 'trabalho acadêmico',
                'verbose_name_plural': 'trabalhos acadêmicos',
                'ordering': ('display_order', '-year', 'title'),
            },
        ),
        migrations.CreateModel(
            name='AcademicWorkContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('author', 'Autor'), ('advisor', 'Orientador'), ('co_advisor', 'Coorientador'), ('examiner', 'Avaliador'), ('collaborator', 'Colaborador')], max_length=32)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('academic_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_contributors', to='research.academicwork')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_work_contributions', to='people.person')),
            ],
            options={
                'verbose_name': 'colaborador de trabalho acadêmico',
                'verbose_name_plural': 'colaboradores de trabalhos acadêmicos',
                'ordering': ('display_order', 'person__full_name'),
            },
        ),
        migrations.AddField(
            model_name='academicwork',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='academic_works', through='research.AcademicWorkContributor', to='people.person'),
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('expected_results', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('project_status', models.CharField(choices=[('planned', 'Planejada'), ('in_progress', 'Em andamento'), ('completed', 'Concluída'), ('suspended', 'Suspensa'), ('canceled', 'Cancelada')], default='planned', max_length=32)),
                ('editorial_status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=32)),
                ('cover_image', models.ImageField(blank=True, upload_to='research/projects/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('legacy_portfolio_project_id', models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True)),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_projects', to='axes.researchaxis')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_projects', to='institutional.institutionalunit')),
            ],
            options={
                'verbose_name': 'pesquisa',
                'verbose_name_plural': 'pesquisas',
                'ordering': ('display_order', '-start_date', 'title'),
            },
        ),
        migrations.AddField(
            model_name='academicwork',
            name='research_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_works', to='research.researchproject'),
        ),
        migrations.CreateModel(
            name='ResearchProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(choices=[('coordinator', 'Coordenador'), ('researcher', 'Pesquisador'), ('advisor', 'Orientador'), ('scholarship_holder', 'Bolsista'), ('volunteer', 'Voluntário'), ('collaborator', 'Colaborador')], default='collaborator', max_length=32)),
                ('is_coordinator', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_project_memberships', to='people.person')),
                ('research_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='research.researchproject')),
            ],
            options={
                'verbose_name': 'membro de pesquisa',
                'verbose_name_plural': 'membros de pesquisa',
                'ordering': ('display_order', 'person__full_name'),
            },
        ),
        migrations.AddField(
            model_name='researchproject',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='research_projects', through='research.ResearchProjectMember', to='people.person'),
        ),
        migrations.AddConstraint(
            model_name='academicworkcontributor',
            constraint=models.UniqueConstraint(fields=('academic_work', 'person', 'role'), name='unique_academic_work_contributor'),
        ),
        migrations.AddConstraint(
            model_name='researchprojectmember',
            constraint=models.UniqueConstraint(fields=('research_project', 'person'), name='unique_research_project_member'),
        ),
        migrations.AddConstraint(
            model_name='researchproject',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('start_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='research_project_valid_date_range'),
        ),
    ]
