# Generated by Django 5.2.16 on 2026-07-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_final_legacy_cut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicwork',
            options={'ordering': ('-year', 'title'), 'verbose_name': 'trabalho acadêmico', 'verbose_name_plural': 'trabalhos acadêmicos'},
        ),
        migrations.AlterModelOptions(
            name='researchproject',
            options={'ordering': ('-start_date', 'title'), 'verbose_name': 'pesquisa', 'verbose_name_plural': 'pesquisas'},
        ),
        migrations.RemoveField(
            model_name='academicwork',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='academicwork',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='academicwork',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='expected_results',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='legacy_portfolio_project_id',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='methodology',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='researchprojectmember',
            name='is_coordinator',
        ),
        migrations.AddField(
            model_name='academicwork',
            name='include_in_parent_ecosystem',
            field=models.BooleanField(default=False, help_text='Inclui este conteúdo no recorte público da unidade mãe.'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='external_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='file',
            field=models.FileField(blank=True, upload_to='research/projects/'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='include_in_parent_ecosystem',
            field=models.BooleanField(default=False, help_text='Inclui este conteúdo no recorte público da unidade mãe.'),
        ),
    ]
