# Generated by Django 5.2.16 on 2026-07-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=180)),
                ('acronym', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('unit_type', models.CharField(choices=[('laboratory', 'Laboratório'), ('academic_league', 'Liga acadêmica'), ('program', 'Programa'), ('research_group', 'Grupo de pesquisa'), ('initiative', 'Iniciativa')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='institutional/logos/')),
                ('cover_image', models.ImageField(blank=True, upload_to='institutional/covers/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='institutional.institutionalunit')),
            ],
            options={
                'verbose_name': 'unidade institucional',
                'verbose_name_plural': 'unidades institucionais',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='InstitutionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(max_length=120)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_memberships', to='people.person')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='institutional.institutionalunit')),
            ],
            options={
                'verbose_name': 'vínculo institucional',
                'verbose_name_plural': 'vínculos institucionais',
                'ordering': ('unit__display_order', 'display_order', 'person__full_name', 'role'),
            },
        ),
    ]
