# Generated by Django 5.2.16 on 2026-07-17 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactmetric',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='impact_metrics', to='institutional.institutionalunit'),
        ),
    ]
