# Generated by Django 5.2.16 on 2026-07-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_validate_and_add_institutional_constraints'),
        ('metrics', '0002_impactmetric_unit'),
        ('research', '0003_final_legacy_cut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactmetric',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impact_metrics', to='institutional.institutionalunit'),
        ),
    ]
