# Generated by Django 5.2.16 on 2026-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180)),
                ('subtitle', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=240)),
                ('image', models.ImageField(blank=True, upload_to='core/heroes/')),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'banner principal',
                'verbose_name_plural': 'banners principais',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='InstitutionalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('section_type', models.CharField(choices=[('mission', 'Missão'), ('vision', 'Visão'), ('values', 'Valores'), ('history', 'Histórico'), ('purpose', 'Propósito')], max_length=32)),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='core/sections/')),
                ('is_published', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'seção institucional',
                'verbose_name_plural': 'seções institucionais',
                'ordering': ('display_order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('site_name', models.CharField(default='LATEC.IN', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('institution', models.CharField(blank=True, max_length=180)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='core/logos/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'configuração do site',
                'verbose_name_plural': 'configurações do site',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('label', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'link social',
                'verbose_name_plural': 'links sociais',
                'ordering': ('display_order', 'label'),
            },
        ),
    ]
