# Generated by Django 5.2.16 on 2026-07-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('institutional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_banners', to='institutional.institutionalunit'),
        ),
        migrations.AddField(
            model_name='institutionalsection',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutional_sections', to='institutional.institutionalunit'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings', to='institutional.institutionalunit'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_links', to='institutional.institutionalunit'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='LABTEC.IN', max_length=120),
        ),
    ]
