# Generated by Django 5.2.16 on 2026-07-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_herobanner_unit_institutionalsection_unit_and_more'),
        ('institutional', '0002_validate_and_add_institutional_constraints'),
        ('research', '0003_final_legacy_cut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herobanner',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hero_banners', to='institutional.institutionalunit'),
        ),
        migrations.AlterField(
            model_name='institutionalsection',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutional_sections', to='institutional.institutionalunit'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_settings', to='institutional.institutionalunit'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='social_links', to='institutional.institutionalunit'),
        ),
    ]
