# Generated by Django 5.2.16 on 2026-07-08 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('axes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('output_type', models.CharField(choices=[('article', 'Artigo'), ('abstract', 'Resumo'), ('patent', 'Patente'), ('ebook', 'E-book'), ('book', 'Livro'), ('technical_report', 'Relatório técnico'), ('project', 'Projeto'), ('scientific_production', 'Produção científica')], max_length=40)),
                ('authors', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, upload_to='scientific/')),
                ('external_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=32)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('axis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_outputs', to='axes.researchaxis')),
            ],
            options={
                'verbose_name': 'produção científica',
                'verbose_name_plural': 'produções científicas',
                'ordering': ('display_order', '-publication_date', 'title'),
            },
        ),
    ]
