# Generated by Django 5.2.16 on 2026-07-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('research', '0001_initial'),
        ('scientific', '0002_scientificoutput_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificoutput',
            name='legacy_portfolio_project_id',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scientificoutput',
            name='academic_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_outputs', to='research.academicwork'),
        ),
        migrations.AddField(
            model_name='scientificoutput',
            name='research_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scientific_outputs', to='research.researchproject'),
        ),
        migrations.CreateModel(
            name='ScientificAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('author_order', models.PositiveIntegerField()),
                ('author_role', models.CharField(blank=True, max_length=120)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_authorships', to='people.person')),
                ('scientific_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='scientific.scientificoutput')),
            ],
            options={
                'verbose_name': 'autoria científica',
                'verbose_name_plural': 'autorias científicas',
                'ordering': ('author_order', 'person__full_name'),
                'constraints': [models.UniqueConstraint(fields=('scientific_output', 'person'), name='unique_scientific_output_person'), models.UniqueConstraint(fields=('scientific_output', 'author_order'), name='unique_scientific_output_author_order')],
            },
        ),
    ]
