# Generated by Django 5.2.16 on 2026-07-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_validate_and_add_institutional_constraints'),
        ('research', '0003_final_legacy_cut'),
        ('scientific', '0003_scientificoutput_academic_work_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scientificoutput',
            options={'ordering': ('-publication_date', 'title'), 'verbose_name': 'produção científica', 'verbose_name_plural': 'produções científicas'},
        ),
        migrations.RemoveField(
            model_name='scientificoutput',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='scientificoutput',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='scientificoutput',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='scientificoutput',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='scientificoutput',
            name='legacy_portfolio_project_id',
        ),
        migrations.RenameField(
            model_name='scientificoutput',
            old_name='status',
            new_name='editorial_status',
        ),
        migrations.AddField(
            model_name='scientificoutput',
            name='include_in_parent_ecosystem',
            field=models.BooleanField(default=False, help_text='Inclui este conteúdo no recorte público da unidade mãe.'),
        ),
        migrations.AlterField(
            model_name='scientificoutput',
            name='output_type',
            field=models.CharField(choices=[('article', 'Artigo'), ('abstract', 'Resumo'), ('patent', 'Patente'), ('ebook', 'E-book'), ('book', 'Livro'), ('technical_report', 'Relatório técnico'), ('other', 'Outro')], max_length=40),
        ),
        migrations.AlterField(
            model_name='scientificoutput',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scientific_outputs', to='institutional.institutionalunit'),
        ),
    ]
