# Generated by Django 5.2.16 on 2026-07-08 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Palavras-chave separadas por vírgula.')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'eixo de atuação',
                'verbose_name_plural': 'eixos de atuação',
                'ordering': ('display_order', 'number'),
            },
        ),
        migrations.CreateModel(
            name='AxisMentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('role', models.CharField(default='Mentor', max_length=120)),
                ('is_main_mentor', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_mentorships', to='people.person')),
                ('axis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorships', to='axes.researchaxis')),
            ],
            options={
                'verbose_name': 'mentoria de eixo',
                'verbose_name_plural': 'mentorias de eixo',
                'ordering': ('axis__number', 'display_order', 'person__full_name'),
                'constraints': [models.UniqueConstraint(fields=('axis', 'person'), name='unique_axis_person_mentorship')],
            },
        ),
    ]
