# Generated by Django 5.2.16 on 2026-07-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_validate_and_add_institutional_constraints'),
        ('portfolio', '0002_project_unit'),
        ('research', '0003_final_legacy_cut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-year', 'title'), 'verbose_name': 'projeto', 'verbose_name_plural': 'projetos'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
        migrations.AddField(
            model_name='project',
            name='include_in_parent_ecosystem',
            field=models.BooleanField(default=False, help_text='Inclui este conteúdo no recorte público da unidade mãe.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='institutional.institutionalunit'),
        ),
    ]
