# Generated by Django 5.2.16 on 2026-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='editorial_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='enrollment_status',
            field=models.CharField(choices=[('open', 'Inscrições abertas'), ('coming_soon', 'Em breve'), ('closed', 'Inscrições encerradas'), ('completed', 'Concluído')], default='coming_soon', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='editorial_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('open', 'Inscrições abertas'), ('completed', 'Realizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=32),
        ),
    ]
