# Generated by Django 5.2.16 on 2026-07-17 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
        ('learning', '0002_remove_course_status_remove_event_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='institutional.institutionalunit'),
        ),
        migrations.AddField(
            model_name='event',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='institutional.institutionalunit'),
        ),
        migrations.AddField(
            model_name='learningtrack',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_tracks', to='institutional.institutionalunit'),
        ),
    ]
