# Generated by Django 5.2.16 on 2026-07-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_validate_and_add_institutional_constraints'),
        ('learning', '0003_course_unit_event_unit_learningtrack_unit'),
        ('research', '0003_final_legacy_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningtrack',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='track',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('-start_date', 'title'), 'verbose_name': 'curso', 'verbose_name_plural': 'cursos'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_published',
        ),
        migrations.AddField(
            model_name='course',
            name='include_in_parent_ecosystem',
            field=models.BooleanField(default=False, help_text='Inclui este conteúdo no recorte público da unidade mãe.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='institutional.institutionalunit'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='LearningTrack',
        ),
    ]
