# Generated by Django 5.2.16 on 2026-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('subject', models.CharField(max_length=160)),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Nova'), ('in_progress', 'Em atendimento'), ('answered', 'Respondida'), ('archived', 'Arquivada')], default='new', max_length=32)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('partner_type', models.CharField(choices=[('academic', 'Acadêmico'), ('institutional', 'Institucional'), ('productive_sector', 'Setor produtivo'), ('community', 'Comunidade'), ('other', 'Outro')], default='institutional', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='partnerships/logos/')),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'parceiro',
                'verbose_name_plural': 'parceiros',
                'ordering': ('display_order', 'name'),
            },
        ),
    ]
