# Generated by Django 5.2.16 on 2026-07-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='contact_type',
            field=models.CharField(choices=[('questions', 'Dúvidas'), ('press', 'Imprensa'), ('partnership', 'Quero ser parceiro'), ('selection_process', 'Processo seletivo'), ('other', 'Outro')], default='other', max_length=32),
        ),
    ]
