# Generated by Django 5.2.16 on 2026-07-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
        ('partnerships', '0002_contactmessage_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='partners', to='institutional.institutionalunit'),
        ),
    ]
