# Generated by Django 5.2.16 on 2026-07-18 18:21

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_profile_scopes(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Unit = apps.get_model("institutional", "InstitutionalUnit")
    AxisMentorship = apps.get_model("axes", "AxisMentorship")

    labtec = Unit.objects.filter(slug="labtec-in").first()
    latec = Unit.objects.filter(slug="latec").first()

    coordinators = Profile.objects.filter(role="coordinator")
    active_coordinator_ids = list(
        coordinators.filter(is_active_admin=True, user__is_active=True).values_list("pk", flat=True)
    )
    coordinators.update(role="lab_coordinator")
    if labtec:
        Profile.objects.filter(pk__in=active_coordinator_ids).update(
            primary_unit_id=labtec.pk,
            inherit_descendants=True,
        )

    if latec:
        mentor_person_ids = AxisMentorship.objects.filter(axis__unit=latec).values_list("person_id", flat=True)
        Profile.objects.filter(
            role="mentor",
            is_active_admin=True,
            user__is_active=True,
            person_id__in=mentor_person_ids,
        ).update(primary_unit_id=latec.pk)


def restore_legacy_profile_roles(apps, schema_editor):
    Profile = apps.get_model("accounts", "Profile")
    Profile.objects.filter(role="lab_coordinator").update(
        role="coordinator",
        primary_unit=None,
        inherit_descendants=False,
    )
    Profile.objects.filter(role="mentor").update(primary_unit=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('axes', '0002_researchaxis_unit'),
        ('institutional', '0002_validate_and_add_institutional_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorized_units',
            field=models.ManyToManyField(blank=True, related_name='authorized_admin_profiles', to='institutional.institutionalunit'),
        ),
        migrations.AddField(
            model_name='profile',
            name='inherit_descendants',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='primary_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_admin_profiles', to='institutional.institutionalunit'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('lab_coordinator', 'Coordenação LABTEC.IN'), ('unit_coordinator', 'Coordenação de unidade'), ('mentor', 'Mentor/Professor'), ('editor', 'Editor'), ('reader', 'Leitor administrativo')], default='reader', max_length=32),
        ),
        migrations.RunPython(migrate_legacy_profile_scopes, restore_legacy_profile_roles),
    ]
