# Generated by Django 5.2.16 on 2026-07-20 22:25

from django.conf import settings
from django.db import migrations, models


def deactivate_removed_roles(apps, schema_editor):
    database = schema_editor.connection.alias
    Profile = apps.get_model("accounts", "Profile")
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    profiles = Profile.objects.using(database).filter(role__in=("admin", "editor", "reader"))
    user_ids = list(profiles.values_list("user_id", flat=True))
    profiles.update(role="unit_coordinator", is_active_admin=False)
    User.objects.using(database).filter(pk__in=user_ids, is_superuser=False).update(is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_institutional_admin_scope'),
        ('research', '0003_final_legacy_cut'),
    ]

    operations = [
        migrations.RunPython(deactivate_removed_roles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('lab_coordinator', 'Coordenação LABTEC.IN'), ('unit_coordinator', 'Coordenação de unidade'), ('mentor', 'Mentor/Professor')], max_length=32),
        ),
    ]
