# Generated by Django 5.2.16 on 2026-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransparencyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('document_type', models.CharField(choices=[('notice', 'Edital'), ('minutes', 'Ata'), ('homologation', 'Homologação'), ('appeal_judgment', 'Julgamento de recurso'), ('result', 'Resultado'), ('statement', 'Comunicado')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='transparency/')),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('related_process', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('in_review', 'Em revisão'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=32)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'documento de transparência',
                'verbose_name_plural': 'documentos de transparência',
                'ordering': ('display_order', '-publication_date', 'title'),
            },
        ),
    ]
