# Generated by Django 5.2.16 on 2026-07-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_validate_and_add_institutional_constraints'),
        ('research', '0003_final_legacy_cut'),
        ('transparency', '0002_transparencydocument_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transparencydocument',
            options={'ordering': ('-publication_date', 'title'), 'verbose_name': 'documento de transparência', 'verbose_name_plural': 'documentos de transparência'},
        ),
        migrations.RemoveField(
            model_name='transparencydocument',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='transparencydocument',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='transparencydocument',
            name='is_published',
        ),
        migrations.RenameField(
            model_name='transparencydocument',
            old_name='status',
            new_name='editorial_status',
        ),
        migrations.AddField(
            model_name='transparencydocument',
            name='include_in_parent_ecosystem',
            field=models.BooleanField(default=False, help_text='Inclui este conteúdo no recorte público da unidade mãe.'),
        ),
        migrations.AlterField(
            model_name='transparencydocument',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transparency_documents', to='institutional.institutionalunit'),
        ),
    ]
