# Generated by Django 5.2.16 on 2026-07-20 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_validate_and_add_institutional_constraints'),
        ('news', '0002_post_unit'),
        ('research', '0003_final_legacy_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at', 'title'), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='post',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='editorial_status',
        ),
        migrations.AddField(
            model_name='post',
            name='include_in_parent_ecosystem',
            field=models.BooleanField(default=False, help_text='Inclui este conteúdo no recorte público da unidade mãe.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='institutional.institutionalunit'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
