# Generated by Django 5.2.16 on 2026-07-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('research', '0003_final_legacy_cut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_featured',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
